# Generated by Django 4.0.2 on 2022-02-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='time',
            field=models.TextField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
