# Generated by Django 4.0.2 on 2022-02-11 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_blogger_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='time',
        ),
    ]
