# Generated by Django 4.0.2 on 2022-02-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_remove_blogger_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
